## This file is a template remove the .template to use the file
##############################################################################################
##    Would Recommend you to refer to Wiki fisrt before making changes to the config file   ##
##                     https://github.com/meisnate12/Plex-Meta-Manager-Wiki                 ##
##############################################################################################
libraries:                                      # This is called out once within the config.yml file                                       
  Movies:                                       # Each library must match the Plex library name
    metadata_path:
      - /config/Movies/Awards.yml
      - /config/Movies/Decades.yml
      - /config/Movies/Genres.yml
      - /config/Movies/Holidays.yml
      - /config/Movies/Studios.yml
      - /config/Movies/Suggestions.yml
      - folder: /config/Movies/                 # This is a local directory on the system
      - git: PMM/chart/basic                    # This is a file within the https://github.com/meisnate12/Plex-Meta-Manager-Configs Repository
      - git: PMM/chart/imdb                     # This is a file within the https://github.com/meisnate12/Plex-Meta-Manager-Configs Repository
      - git: PMM/chart/trakt
    overlay_path:
      - remove_overlays: false                  # Set this to true to remove all overlays
      - file: /config/Movies/MoviesOverlays.yml      # This is a local file on the system
      - git: PMM/overlays/imdb_top_250          # This is a file within the https://github.com/meisnate12/Plex-Meta-Manager-Configs Repository
    settings:
      missing_path: config/missing
      asset_directory:
      - config/assets/
      - config/assets/movies
      - config/assets/awards
      - config/assets/collections
      - config/assets/decades
      - config/assets/genres
      - config/assets/holidays
      - config/assets/studios
      - config/assets/suggestions
    operations:
      assets_for_all: false
      split_duplicates: false
      delete_unmanaged_collections: true    
  TV Shows:                           
    metadata_path:
      - file: /config/TV/Networks.yml
      - folder: /config/TV
      - git: PMM/chart/basic                    # This is a file within the https://github.com/meisnate12/Plex-Meta-Manager-Configs Repository
      - git: PMM/chart/imdb                     # This is a file within the https://github.com/meisnate12/Plex-Meta-Manager-Configs Repository
  TV Shows - 4K:
    metadata_path:
      - file: /config/TV/4ktv.yml
    overlay_path:
      - remove_overlays: false
      - file: /config/TV/4ktvoverlays.yml   
  Music:
    metadata_path:
      - file: config/Music.yml
  playlist_files:
      - file: config/Playlists.yml       
      - git: PMM/playlist                           # This is a file within the https://github.com/meisnate12/Plex-Meta-Manager-Configs Repository
settings: # Can be individually specified per library as well
  asset_folders: true
  asset_depth: 3
  asset_directory: config/assets
  cache: true
  cache_expiration: 60
  check_nightly: false  
  create_asset_folders: true
  create_asset_directories: true
  custom_repo:
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  dimensional_asset_rename: true
  download_url_assets: true
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  minimum_items: 2
  missing_only_released: true
  missing_path: config/missing
  only_filter_missing: false
  prioritize_assets: false
  playlist_report: true
  playlist_sync_to_users: all
  run_again_delay: 2
  save_report: true
  show_asset_not_needed: true
  show_filtered: true
  show_options: true
  show_missing: false
  show_missing_assets: false
  show_missing_season_assets: false
  save_missing: false
  show_missing_episode_assets: true
  show_unmanaged: true
  sync_mode: append
  tvdb_language: eng
  verify_ssl: true
webhooks:                                       # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
plex:                                           # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://192.168.1.103:32400
  token: RRHe-R4bHCWdyK7cJpHb
  timeout: 60
  clean_bundles: true
  empty_trash: true
  optimize: false
tmdb:                                           # REQUIRED for the script to run
  apikey: d876bab76198fc68ddc6d6600f9343f8
  language: en
tautulli:                                       # Can be individually specified per library as well
  url: http://192.168.1.103:8181
  apikey: 1571a26cfa394540a713ae7026062faf
mdblist:
  apikey: 9njbrumoammztv7fjg2js0r8r
  cache_expiration: 60
radarr:                                         # Can be individually specified per library as well
  url: http://192.168.1.103:36878
  token: a3e022f7c1344c0198057df7d716cd83
  add_missing: false
  add_existing: false
  root_folder_path: /share/data/media/New Movies/
  monitor: true
  availability: announced
  quality_profile: HD-1080p
  tag:
  search: true
  radarr_path:
  plex_path:
sonarr:                                         # Can be individually specified per library as well
  url: http://192.168.1.103:35989
  token: da3f07cf2a8341a3adef09557887a645
  add_missing: false
  add_existing: false
  root_folder_path:/share/data/media/tv
  monitor: all
  quality_profile: HD-1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:/share/data/media/tv
  plex_path:
trakt:
  client_id: 2f84f7cb032d60b9901566e29772d2f02f1e5cd06db52febd88ab583afc58d78
  client_secret: 328386e0815ff44e5cfdcef9a587482be136e8e2a55bf9fe72086586513f396f
  pin:
  authorization:
    # everything below is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:
    scope: public
    created_at: