# TV Metadata
metadata:
  Paw Patrol:
    url_poster: https://theposterdb.com/api/assets/166740
    seasons:
      1:
        url_poster: https://theposterdb.com/api/assets/167596
      2:
        url_poster: https://theposterdb.com/api/assets/167597
      3:
        url_poster: https://theposterdb.com/api/assets/167598
      4:
        url_poster: https://theposterdb.com/api/assets/167599
  The Walking Dead:
    url_poster: https://theposterdb.com/api/assets/70254
    seasons:
      1: 
        url_poster: https://theposterdb.com/api/assets/70256
      2: 
        url_poster: https://theposterdb.com/api/assets/70257
      3: 
        url_poster: https://theposterdb.com/api/assets/70258
      4: 
        url_poster: https://theposterdb.com/api/assets/70259
      5: 
        url_poster: https://theposterdb.com/api/assets/70260
      6: 
        url_poster: https://theposterdb.com/api/assets/70261
      7: 
        url_poster: https://theposterdb.com/api/assets/70262
      8: 
        url_poster: https://theposterdb.com/api/assets/70263
      9: 
        url_poster: https://theposterdb.com/api/assets/70264
      10:  
        url_poster: https://theposterdb.com/api/assets/70265
  The Big Bang Theory:
    url_poster: https://theposterdb.com/api/assets/36303
    seasons:
      1: 
        url_poster: https://theposterdb.com/api/assets/36305
      2: 
        url_poster: https://theposterdb.com/api/assets/36306
      3: 
        url_poster: https://theposterdb.com/api/assets/36307
      4: 
        url_poster: https://theposterdb.com/api/assets/36308
      5: 
        url_poster: https://theposterdb.com/api/assets/36309
      6: 
        url_poster: https://theposterdb.com/api/assets/36310
      7: 
        url_poster: https://theposterdb.com/api/assets/36311
      8: 
        url_poster: https://theposterdb.com/api/assets/36312
      9: 
        url_poster: https://theposterdb.com/api/assets/36313
      10:  
        url_poster: https://theposterdb.com/api/assets/36314
      11:  
        url_poster: https://theposterdb.com/api/assets/36315
      12:  
        url_poster: https://theposterdb.com/api/assets/36316