##########################################################################
##########################################################################
##                                       _ _    _                       ##
##             _ __ ___  _ __ __ _ _ __ (_) | _(_)                      ##
##            | '_ ` _ \| '__/ _` | '_ \| | |/ / |                      ##
##            | | | | | | | | (_| | | | | |   <| |                      ##
##            |_| |_| |_|_|  \__,_|_| |_|_|_|\_\_|                      ##
##                                                                      ##
##                                                                      ##
##               Collection for Plex-Meta-Manager                       ##
##########################################################################
##########################################################################

#   +01_ = Charts
#   +02_ = Holidays
#   +03_ = Studios or Network
#   +04_ = Collection
#   +05_ = Countries
#   +06_ = Genres
#   +07_ = Awards
#   +08_ = Decades
#   +09_ = People
#   +10_ = Movies

#####################################################
#            Holidays Collections                   #
#####################################################
templates:
  Holidays:
    sort_title: +02_<<collection_name>>
    sync_mode: sync

collections:
    Halloween:
      template: { name: Holidays}
      trakt_list:
        - https://trakt.tv/users/29zombies/lists/halloween
        - https://trakt.tv/users/galacticboy/lists/not-so-spooky-halloween
       # - https://trakt.tv/users/kairbear08/lists/halloween
       # - https://trakt.tv/users/mybicycle/lists/halloween
       # - https://trakt.tv/users/jayinftl/lists/halloween
       # - https://trakt.tv/users/roswellgeek/lists/halloween
      summary: "Boo!"
      sort_title: +20_<<collection_name>>
      visible_library: false
      visible_home: false
      visible_shared: false
 #    schedule: yearly (08/28)      

    Thanksgiving:
      template: { name: Holidays}
      trakt_list:
        - https://trakt.tv/users/galacticboy/lists/thanksgiving-movies
        - https://trakt.tv/users/shahid1296/lists/thanksgiving
        - https://trakt.tv/users/retrogran/lists/thanksgiving-season-movies
        - https://trakt.tv/users/padawan_seneca/lists/vibe-autumn-tv-series-movies
      sort_title: +20_<<collection_name>>
      visible_home: false
      visible_shared: false
      visible_library: false
      #   schedule: yearly (09/10)


    Christmas:
      template: { name: Holidays}
      trakt_list:
        - https://trakt.tv/users/movistapp/lists/christmas-movies
        - https://trakt.tv/users/questdvd/lists/absolute-hayes-christmas-classics
        - https://trakt.tv/users/littlestella3/lists/christmas
      sort_title: +20_<<collection_name>>
      summary: "Ho ho ho"
      visible_home: false
      visible_shared: false
      visible_library: false
  #    schedule: yearly (10/01)


    Chinese New Year:
      template: { name: Holidays}
      trakt_list: 
       - https://trakt.tv/users/mraniki/lists/cny
      visible_library: true
      visible_home: true
      visible_shared: true
      smart_label: audience_rating.desc
      summary: Gong Xi Fa Cai !
     #schedule: yearly (04/01) 

    Valentine's Day:
      template: { name: Holidays}
      trakt_list: 
       - https://trakt.tv/users/movie-pal/lists/valentine-s-day
       - https://trakt.tv/users/barsaky/lists/den-svateho-valentina-valentine-s-day
       - https://trakt.tv/users/abbelea/lists/movies-best-of-love
      summary: Love me tender, love me sweet
      visible_library: false
      visible_home: false
      visible_shared: false
      sort_title: +20_<<collection_name>>
       #   schedule: yearly (02/02)

    St. Patrick's Day:
      template: { name: Holidays}
      trakt_list: 
        - https://trakt.tv/users/triadcool/lists/irish
        - https://trakt.tv/users/sympli/lists/st-patricks-day-movies
      visible_library: false
      visible_home: false
      visible_shared: false
      summary: a cultural and religious celebration held on 17 March, the traditional death date of Saint Patrick the foremost patron saint of Ireland. 
      sort_title: +20_<<collection_name>>
      #   schedule: yearly (03/01)
 
    Eid:
      template: { name: Holidays}
      trakt_list: 
       - https://trakt.tv/users/mraniki/lists/eid
      visible_library: false
      visible_home: false
      visible_shared: false
      summary: The religious holiday is celebrated by Muslims worldwide because it marks the end of the month-long dawn-to-sunset fasting of Ramadan.
      sort_title: +20_<<collection_name>>
     #   schedule: yearly (03/15) 
    
    Diwali:
      template: { name: Holidays}
      trakt_list: 
       - https://trakt.tv/users/mraniki/lists/diwali 
      visible_library: false
      visible_home: false
      visible_shared: false
      summary: One of the most popular festivals of Hinduism, Diwali symbolizes the spiritual "victory of light over darkness, good over evil, and knowledge over ignorance".
      sort_title: +20_<<collection_name>>
         # schedule: yearly (10/01) 


     


