##########################################################################
##########################################################################
##                                       _ _    _                       ##
##             _ __ ___  _ __ __ _ _ __ (_) | _(_)                      ##
##            | '_ ` _ \| '__/ _` | '_ \| | |/ / |                      ##
##            | | | | | | | | (_| | | | | |   <| |                      ##
##            |_| |_| |_|_|  \__,_|_| |_|_|_|\_\_|                      ##
##                                                                      ##
##                                                                      ##
##               Collection for Plex-Meta-Manager                       ##
##########################################################################
##########################################################################

#   +01_ = Charts
#   +02_ = Holidays
#   +03_ = Studios or Network
#   +04_ = Collection
#   +05_ = Countries
#   +06_ = Genres
#   +07_ = Awards
#   +08_ = Decades
#   +09_ = People
#   +10_ = Movies

#####################################################
#                   Collections                     #
#####################################################




templates:

  Trakt:
    sort_title: +04_<<collection_name>>
    sync_mode: sync
    url_background: https://img5.goodfon.com/original/1920x1080/1/61/fon-netflix-logo-raduga-tsvet-fon-background-skachat-oboi-sk.jpg
    collection_order: custom

  TraktMulti:
    sort_title: +04_<<collection_name>>
    sync_mode: sync
    url_background: https://img5.goodfon.com/original/1920x1080/1/61/fon-netflix-logo-raduga-tsvet-fon-background-skachat-oboi-sk.jpg
    collection_order: release    

collections:
  TV Show Francais:
    template: { name: TraktMulti}
    trakt_list_details: 
      - https://trakt.tv/users/mraniki/lists/french-series
      - https://trakt.tv/users/mraniki/lists/tele

  IMDB Top Rated:
    template: { name: Trakt} 
    trakt_list_details: 
      - https://trakt.tv/users/justin/lists/imdb-top-rated-movies

  Criterion:
    template: { name: Trakt} 
    trakt_list_details:
      - https://trakt.tv/users/maxwelldeux/lists/the-criterion-collection

  1001 Movies You Must See Before You Die:
    template: { name: Trakt} 
    trakt_list_details: 
      - https://trakt.tv/users/sp1ti/lists/1001-movies-you-must-see-before-you-die

  Star Trek:
    template: { name: Trakt} 
    url_background: https://i.redd.it/vz20prnp8v551.jpg
    trakt_list_details: 
      - https://trakt.tv/users/dgw/lists/star-trek-canon

  Star Wars:
    template: { name: TraktMulti} 
    url_background: https://images.unsplash.com/photo-1579566346927-c68383817a25
    trakt_list_details: 
      - https://trakt.tv/users/ruben_vw_/lists/star-wars-canon-timeline
      - https://trakt.tv/users/darkman1498/lists/star-wars

  Battlestar Galactica:
    template: { name: Trakt} 
    url_background: https://wallpapercave.com/wp/vPJGO64.jpg
    url_poster: https://theposterdb.com/api/assets/160915
    trakt_list_details: 
      - https://trakt.tv/users/mraniki/lists/battlestar-galactica-universe

  Shakespeare:
    template: { name: Trakt} 
    url_background: https://images.unsplash.com/photo-1598391990342-311775e3d374
    trakt_list_details:
      - https://trakt.tv/users/michaeldibben/lists/shakespeare-plays





