##########################################################################
##########################################################################
##                                       _ _    _                       ##
##             _ __ ___  _ __ __ _ _ __ (_) | _(_)                      ##
##            | '_ ` _ \| '__/ _` | '_ \| | |/ / |                      ##
##            | | | | | | | | (_| | | | | |   <| |                      ##
##            |_| |_| |_|_|  \__,_|_| |_|_|_|\_\_|                      ##
##                                                                      ##
##       Tranquille. Il a deux trous rouges au côté droit.              ##
##               Collection for Plex-Meta-Manager                       ##
##########################################################################
##########################################################################

#   +01_ = Charts
#   +02_ = Holidays
#   +03_ = Studios or Network
#   +04_ = Collection
#   +05_ = Countries
#   +06_ = Genres
#   +07_ = Awards
#   +08_ = Decades
#   +09_ = People
#   +10_ = Movies

#####################################################
#           Countries Collections                   #
#####################################################

templates:
  SFF Template:
    sort_title: '+05_collection<<year>>'
    smart_label: audience_rating.desc
    summary: 'Sundance Film Festival of <<year>>'
    sync_mode: append
    trakt_list: https://trakt.tv/users/vermelholimao/lists/sundance-film-festival-<<year>>
    item_label: Sundance Film Festival
  SFF Genre Template:
    sort_title: '*Sundance Film Festival <<genre>>'
    smart_label: audience_rating.desc
    smart_filter:
      all:
        label: Sundance Film Festival
        genre: <<genre>>
    summary: 'Sundance Film Festival: <<genre>>'
    sync_mode: append
    
collections:


  Korean Cinema:
    trakt_list: 
      - https://trakt.tv/users/sp1ti/lists/lovehkfilm-s-top-100-hong-kong-films-of-the-ninetie
      - https://trakt.tv/users/c858/lists/korean-movies
    sync_mode: sync
    sort_title: "+05_collection_Z_Korean Cinema"
    summary: "Korean movies"
    smart_label: audience_rating.desc

  Japan Cinema:
    schedule: weekly(sunday)
    sort_title: +05_collection_Z_Japan Cinema
    summary: A collection of Japanese Films.
    sync_mode: sync
    smart_filter:
      all:        
        audio_language: ja
      sort_by: release.desc 

  HKG Cinema:
    schedule: weekly(sunday)
    sort_title: +05_collection_Z_hk
    summary: A collection of Hong Kong Films.
    sync_mode: sync
    smart_filter:
      all:        
        country: Hong Kong
      sort_by: release.desc 


