#   __                                        _      ____  ____   ___ ____  ____  
#  / _\_   _ _ __   ___ _ __ /\/\   __ _ _ __(_) ___|___ \|___ \ / _ \___ \|___ \ 
#  \ \| | | | '_ \ / _ \ '__/    \ / _` | '__| |/ _ \ __) | __) | (_) |__) | __) |
#  _\ \ |_| | |_) |  __/ | / /\/\ \ (_| | |  | | (_) / __/ / __/ \__, / __/ / __/ 
#  \__/\__,_| .__/ \___|_| \/    \/\__,_|_|  |_|\___/_____|_____|  /_/_____|_____|
#           |_|                                                                   

collections:
  Winter 2010 Anime:
    mal_season:
      season: winter
      year: 2010
    sync_mode: sync
  Spring 2010 Anime:
    mal_season:
      season: spring
      year: 2010
    sync_mode: sync
  Summer 2010 Anime:
    mal_season:
      season: summer
      year: 2010
    sync_mode: sync
  Fall 2010 Anime:
    mal_season:
      season: fall
      year: 2010
    sync_mode: sync
  
  Winter 2011 Anime:
    mal_season:
      season: winter
      year: 2011
    sync_mode: sync
  Spring 2011 Anime:
    mal_season:
      season: spring
      year: 2011
    sync_mode: sync
  Summer 2011 Anime:
    mal_season:
      season: summer
      year: 2011
    sync_mode: sync
  Fall 2011 Anime:
    mal_season:
      season: fall
      year: 2011
    sync_mode: sync
  
  Winter 2012 Anime:
    mal_season:
      season: winter
      year: 2012
    sync_mode: sync
  Spring 2012 Anime:
    mal_season:
      season: spring
      year: 2012
    sync_mode: sync
  Summer 2012 Anime:
    mal_season:
      season: summer
      year: 2012
    sync_mode: sync
  Fall 2012 Anime:
    mal_season:
      season: fall
      year: 2012
    sync_mode: sync
    
  Winter 2013 Anime:
    mal_season:
      season: winter
      year: 2013
    sync_mode: sync
  Spring 2013 Anime:
    mal_season:
      season: spring
      year: 2013
    sync_mode: sync
  Summer 2013 Anime:
    mal_season:
      season: summer
      year: 2013
    sync_mode: sync
  Fall 2013 Anime:
    mal_season:
      season: fall
      year: 2013
    sync_mode: sync
        
  Winter 2014 Anime:
    mal_season:
      season: winter
      year: 2014
    sync_mode: sync
  Spring 2014 Anime:
    mal_season:
      season: spring
      year: 2014
    sync_mode: sync
  Summer 2014 Anime:
    mal_season:
      season: summer
      year: 2014
    sync_mode: sync
  Fall 2014 Anime:
    mal_season:
      season: fall
      year: 2014
    sync_mode: sync
        
  Winter 2015 Anime:
    mal_season:
      season: winter
      year: 2015
    sync_mode: sync
  Spring 2015 Anime:
    mal_season:
      season: spring
      year: 2015
    sync_mode: sync
  Summer 2015 Anime:
    mal_season:
      season: summer
      year: 2015
    sync_mode: sync
  Fall 2015 Anime:
    mal_season:
      season: fall
      year: 2015
    sync_mode: sync
        
  Winter 2016 Anime:
    mal_season:
      season: winter
      year: 2016
    sync_mode: sync
  Spring 2016 Anime:
    mal_season:
      season: spring
      year: 2016
    sync_mode: sync
  Summer 2016 Anime:
    mal_season:
      season: summer
      year: 2016
    sync_mode: sync
  Fall 2016 Anime:
    mal_season:
      season: fall
      year: 2016
    sync_mode: sync
            
  Winter 2017 Anime:
    mal_season:
      season: winter
      year: 2017
    sync_mode: sync
  Spring 2017 Anime:
    mal_season:
      season: spring
      year: 2017
    sync_mode: sync
  Summer 2017 Anime:
    mal_season:
      season: summer
      year: 2017
    sync_mode: sync
  Fall 2017 Anime:
    mal_season:
      season: fall
      year: 2017
    sync_mode: sync
                
  Winter 2018 Anime:
    mal_season:
      season: winter
      year: 2018
    sync_mode: sync
  Spring 2018 Anime:
    mal_season:
      season: spring
      year: 2018
    sync_mode: sync
  Summer 2018 Anime:
    mal_season:
      season: summer
      year: 2018
    sync_mode: sync
  Fall 2018 Anime:
    mal_season:
      season: fall
      year: 2018
    sync_mode: sync
                    
  Winter 2019 Anime:
    mal_season:
      season: winter
      year: 2019
    sync_mode: sync
  Spring 2019 Anime:
    mal_season:
      season: spring
      year: 2019
    sync_mode: sync
  Summer 2019 Anime:
    mal_season:
      season: summer
      year: 2019
    sync_mode: sync
  Fall 2019 Anime:
    mal_season:
      season: fall
      year: 2019
    sync_mode: sync
                        
  Winter 2020 Anime:
    mal_season:
      season: winter
      year: 2020
    sync_mode: sync
  Spring 2020 Anime:
    mal_season:
      season: spring
      year: 2020
    sync_mode: sync
  Summer 2020 Anime:
    mal_season:
      season: summer
      year: 2020
    sync_mode: sync
  Fall 2020 Anime:
    mal_season:
      season: fall
      year: 2020
    sync_mode: sync
    
                        
  Winter 2021 Anime:
    mal_season:
      season: winter
      year: 2021
    sync_mode: sync
  Spring 2021 Anime:
    mal_season:
      season: spring
      year: 2021
    sync_mode: sync
  Summer 2021 Anime:
    mal_season:
      season: summer
      year: 2021
    sync_mode: sync
  Fall 2021 Anime:
    mal_season:
      season: fall
      year: 2021
    sync_mode: sync
